export const D = {
  pc:{l:"PC",i:"🖥️",c:"#3b82f6"},laptop:{l:"Laptop",i:"💻",c:"#6366f1"},
  server:{l:"Server",i:"🗄️",c:"#10b981"},web:{l:"Web Server",i:"🌐",c:"#06b6d4"},
  router:{l:"Router",i:"📡",c:"#f59e0b"},l3sw:{l:"L3 Switch",i:"🔀",c:"#f97316"},
  switch:{l:"Switch",i:"⬡",c:"#a78bfa"},hub:{l:"Hub",i:"⬡",c:"#a78bfa"},
  firewall:{l:"Firewall",i:"🛡️",c:"#ef4444"},ngfw:{l:"NGFW",i:"🛡️",c:"#dc2626"},
  ap:{l:"WiFi AP",i:"📶",c:"#06b6d4"},cloud:{l:"Internet",i:"☁️",c:"#64748b"},
  dns:{l:"DNS",i:"🔍",c:"#34d399"},lb:{l:"Load Balancer",i:"⚖️",c:"#f472b6"}
};

export const PR = {
  ICMP:{c:"#ffd700",port:null,l:"L3 — no ports",info:"Used for ping, traceroute, and network diagnostics. ICMP Echo Request (type 8) and Echo Reply (type 0) form the basis of 'ping'. No ports — operates at Layer 3 directly. Routers use ICMP Time Exceeded to signal TTL expiry for traceroute."},
  TCP:{c:"#00ddff",port:"var",l:"L4 — reliable",info:"Connection-oriented. 3-way handshake (SYN→SYN-ACK→ACK). Sequence numbers ensure ordering. ACKs confirm delivery. Retransmission on timeout. Flow control via sliding window. Congestion control: CWND, slow start, AIMD."},
  UDP:{c:"#00ff88",port:"var",l:"L4 — fast",info:"Connectionless, no guarantee. No handshake, no retransmit, no ordering. Faster and lower overhead than TCP. Used for DNS, DHCP, streaming, VoIP, online gaming. Applications implement reliability if needed (QUIC, custom protocols)."},
  HTTP:{c:"#60a5fa",port:"80",l:"L7 — web",info:"GET/POST/PUT/DELETE over TCP port 80. Stateless. HTTP/1.1 uses persistent connections. HTTP/2 adds multiplexed streams over TLS. HTTP/3 runs over QUIC (UDP). Headers carry Host, Content-Type, Authorization, cookies."},
  HTTPS:{c:"#34d399",port:"443",l:"L7 — secure web",info:"HTTP over TLS. TLS 1.3 does 1-RTT handshake: ClientHello with supported ciphers → ServerHello + certificate → Finished. Uses ECDHE for perfect forward secrecy. Data encrypted with symmetric AES-GCM after handshake."},
  DNS:{c:"#a855f7",port:"53",l:"L7 — name resolution",info:"UDP port 53 (TCP for zone transfers). Recursive resolution: client → recursive resolver → root → TLD → authoritative. TTL caches responses. DNSSEC adds RRSIG records. Types: A, AAAA, MX, CNAME, NS, TXT, PTR, SRV."},
  DHCP:{c:"#fb923c",port:"67/68",l:"L7 — IP assignment",info:"UDP broadcast. 4-step DORA: Discover (client broadcasts) → Offer (server proposes IP) → Request (client accepts) → ACK (server confirms). Assigns IP, subnet mask, default gateway, DNS, lease time. Uses relay agents for cross-VLAN delivery."},
  ARP:{c:"#f472b6",port:null,l:"L2 — MAC discovery",info:"Resolves IP to MAC within a subnet. Client broadcasts 'Who has 10.0.0.1?' All hosts in L2 domain receive it. Owner replies with its MAC. Cached in ARP table (minutes). Gratuitous ARP announces IP ownership. Proxy ARP and ARP spoofing are key attack vectors."},
  BGP:{c:"#ef4444",port:"179",l:"L4 — inter-AS routing",info:"TCP port 179. eBGP between different ASes; iBGP inside. Exchanges path vectors (AS_PATH attribute). BGP selects best route by: Local Preference → AS_PATH length → MED → eBGP > iBGP → IGP metric. Powers the entire Internet routing table."},
  OSPF:{c:"#f97316",port:null,l:"L3 — link-state IGP",info:"IP protocol 89. Dijkstra's shortest path first (SPF) algorithm on the full topology map (LSDB). Routers exchange LSAs: Router-LSA, Network-LSA, Summary-LSA. Areas reduce LSDB size. Convergence is fast — sub-second with BFD."}
};

export const OSI_DATA = [
  {n:7,name:"Application",c:"#ef4444",proto:"HTTP, HTTPS, DNS, DHCP, FTP, SMTP, SSH, SNMP, BGP",d:"User-facing protocols. PDU = Data.",detail:"The application layer is where user-data meets the network. Protocols define message syntax, semantics, and session rules. HTTP is stateless — each request is independent unless cookies or tokens maintain state. DNS is the phonebook: apps resolve names to IPs before connecting. SMTP transfers email between mail servers on TCP 25."},
  {n:6,name:"Presentation",c:"#f97316",proto:"TLS/SSL, MIME, Base64, JPEG, MPEG, Protobuf, JSON",d:"Encoding, encryption, compression. PDU = Data.",detail:"Often merged with Application in practice. TLS encrypts data here before it goes to TCP. MIME encoding wraps binary email attachments. Protobuf and MessagePack serialize structured data efficiently."},
  {n:5,name:"Session",c:"#eab308",proto:"NetBIOS, RPC, SIP, H.323, NFS, SQL sessions",d:"Session open/close, checkpointing. PDU = Data.",detail:"Manages dialog control between applications. SIP sets up voice/video calls (signaling), then RTP carries the media. NFS uses RPC for remote file access sessions. SQL connections maintain a session with state."},
  {n:4,name:"Transport",c:"#22c55e",proto:"TCP, UDP, SCTP, QUIC, DCCP, TLS (handshake)",d:"Port numbers, reliability, flow control. PDU = Segment/Datagram.",detail:"TCP segments carry: sequence number, ACK number, window size, flags (SYN/ACK/FIN/RST/PSH). The 3-way handshake establishes state on both ends. UDP datagrams have just src port, dst port, length, checksum (8 bytes total). QUIC runs over UDP but adds stream multiplexing and TLS 1.3 built-in — used by HTTP/3."},
  {n:3,name:"Network",c:"#3b82f6",proto:"IPv4, IPv6, ICMP, ICMPv6, IGMP, OSPF, BGP, MPLS",d:"IP addressing, routing, TTL, fragmentation. PDU = Packet.",detail:"IPv4 header: version, IHL, DSCP, total length, ID, flags, fragment offset, TTL, protocol, checksum, src IP, dst IP. TTL decremented at each router hop — reaches 0 → ICMP Time Exceeded → traceroute. Routers consult FIB for longest-prefix match."},
  {n:2,name:"Data Link",c:"#8b5cf6",proto:"Ethernet 802.3, WiFi 802.11, PPP, VLAN 802.1Q, MPLS",d:"MAC addresses, frames, CRC, switches. PDU = Frame.",detail:"Ethernet frame: preamble (7B) + SFD (1B) + dst MAC (6B) + src MAC (6B) + EtherType (2B) + payload (46-1500B) + FCS (4B CRC). Switches learn MACs per-port in CAM table. 802.1Q VLAN tag is a 4-byte field inserted after src MAC."},
  {n:1,name:"Physical",c:"#ec4899",proto:"Copper Cat5e/6, Fiber SMF/MMF, 802.11 radio, 5G NR",d:"Bits on wire/air/fiber. PDU = Bits.",detail:"Cat6A copper: 10 Gbps to 100m. Single-mode fiber: hundreds of km range. Multi-mode fiber: up to ~500m. WiFi 802.11ax (WiFi 6): OFDMA subcarrier allocation, 1024-QAM, BSS coloring for dense deployments."}
];

export const DEVINFO = {
  router:"Routers operate at Layer 3. They maintain a routing table (RIB) and forwarding table (FIB). Each interface is in a different subnet. Static routes, OSPF, EIGRP, and BGP populate the RIB. NAT/PAT translates private RFC1918 addresses to public IPs.",
  l3sw:"Layer 3 switches combine MAC learning of L2 switches with IP routing. Inter-VLAN routing: each VLAN gets an SVI (switched virtual interface) acting as its default gateway. Much faster than a separate router for intra-datacenter traffic.",
  switch:"L2 switches forward Ethernet frames using the CAM table — a hardware-assisted MAC-to-port mapping. Unknown unicast frames are flooded to all ports. VLAN trunks carry 802.1Q tagged frames. Spanning Tree Protocol (STP/RSTP/MSTP) blocks redundant links.",
  firewall:"Zone-based firewalls partition interfaces into security zones (Inside/Outside/DMZ). Stateful inspection tracks TCP/UDP sessions. ACLs match on src/dst IP, port, protocol. NGFW adds Layer 7 app identification, URL filtering, IPS signatures, TLS inspection.",
  ngfw:"Next-Generation Firewalls add application awareness via deep packet inspection beyond Layer 4. Features: App-ID identifies apps by payload patterns; User-ID maps traffic to AD users; IPS detects exploits; SSL/TLS decryption for east-west inspection.",
  lb:"Load balancers distribute traffic across a pool of servers. L4 LBs route by IP/port only. L7 LBs inspect HTTP headers for content-based routing. Algorithms: Round Robin, Least Connections, IP Hash. Health checks detect failed backends.",
  server:"Servers bind to a well-known TCP/UDP port. The kernel listens with a backlog queue. Each connection gets a new socket (5-tuple). Nginx and HAProxy are event-driven, handling 50k+ concurrent connections.",
  web:"Web servers handle HTTP/HTTPS. HTTPS requires TLS certificate (X.509), private key, CA chain. TLS 1.3 handshake: ClientHello → ServerHello+Cert → CertVerify → Finished. 1 RTT. HSTS pins HTTPS.",
  dns:"DNS resolves FQDNs hierarchically: Recursive resolver → Root → TLD → Authoritative nameserver. UDP port 53. DNSSEC adds cryptographic signing. Records: A, AAAA, MX, CNAME, NS, TXT, PTR, SRV.",
  ap:"802.11ax (WiFi 6) uses OFDMA — multiple clients share the same channel on different subcarriers. MU-MIMO: up to 8 spatial streams. WPA3-SAE replaces WPA2-PSK with a Diffie-Hellman key exchange.",
  hub:"Hubs are Layer 1 repeaters — all ports share one collision domain. Every bit received is re-broadcast to every other port. CSMA/CD managed collisions. Half-duplex only. 10/100 Mbps. Completely obsolete.",
  pc:"End hosts run the full TCP/IP stack in the OS kernel. On startup: DHCP DORA to get IP/mask/gateway/DNS. To communicate outside the subnet: ARP for gateway MAC → send packet to gateway. DNS query to resolve hostname.",
  laptop:"Wireless clients authenticate to the AP via WPA3-SAE association. 4-way handshake derives PTK for unicast encryption. After association, standard DHCP/ARP/TCP stack applies.",
  cloud:"The Internet core is ~100,000 BGP Autonomous Systems. Each AS advertises its IP prefixes via eBGP. Tier-1 ISPs: Cogent, NTT, Level3/Lumen. Content providers peer directly at IXPs. Anycast routes the same prefix from multiple locations."
};

export const LINK_PRESETS = {
  auto:{label:"Auto",c:"#9ab5cc",bw:1000,lat:2,medium:"Smart inference",duplex:"full",dash:"none",stroke:1.8,desc:"Auto-picks a sensible type from the endpoints."},
  ethernet:{label:"Ethernet",c:"#00ddff",bw:1000,lat:2,medium:"Copper / RJ-45",duplex:"full",dash:"none",stroke:1.9,desc:"Standard wired LAN link."},
  fiber:{label:"Fiber",c:"#00ff88",bw:10000,lat:1,medium:"Fiber optic",duplex:"full",dash:"none",stroke:2.4,desc:"High-speed optical uplink / backbone."},
  wifi24:{label:"2.4GHz Wi‑Fi",c:"#a78bfa",bw:150,lat:8,medium:"802.11 wireless",duplex:"half",dash:"7 4",stroke:1.7,desc:"Longer range, slower wireless link."},
  wifi5:{label:"5GHz Wi‑Fi",c:"#8b5cf6",bw:600,lat:5,medium:"802.11ac/ax",duplex:"half",dash:"5 4",stroke:1.8,desc:"Faster Wi‑Fi with shorter range."},
  dns:{label:"DNS",c:"#f472b6",bw:50,lat:12,medium:"Service flow",duplex:"full",dash:"2 5",stroke:1.7,desc:"Logical DNS service path / query link."},
  wan:{label:"WAN",c:"#f59e0b",bw:100,lat:22,medium:"ISP / Internet",duplex:"full",dash:"10 4",stroke:1.9,desc:"Provider edge / Internet handoff."},
  vpn:{label:"VPN",c:"#ffc700",bw:100,lat:28,medium:"Encrypted tunnel",duplex:"full",dash:"8 4 2 4",stroke:1.9,desc:"Encrypted site-to-site tunnel."},
  trunk:{label:"Trunk",c:"#06b6d4",bw:40000,lat:1,medium:"802.1Q trunk",duplex:"full",dash:"none",stroke:2.3,desc:"Tagged multi-VLAN uplink."},
  direct:{label:"Direct",c:"#9bd0ff",bw:1000,lat:1,medium:"Direct connection",duplex:"full",dash:"none",stroke:1.7,desc:"Generic direct link."}
};

export const LINK_CHOICES = ["auto","ethernet","fiber","wifi24","wifi5","dns","wan","vpn","trunk","direct"];

export const SIM_PROFILES = {
  normal:{label:"Normal",loss:0.002,latAdd:0,bwScale:1,desc:"Balanced traffic and stable links."},
  poorwifi:{label:"Poor Wi‑Fi",loss:0.06,latAdd:38,bwScale:0.38,desc:"Weak signal, retries, jitter, and visible lag."},
  congested:{label:"Congested",loss:0.03,latAdd:24,bwScale:0.62,desc:"Busy network with queueing and slower response."},
  fiber:{label:"Fiber",loss:0.0005,latAdd:0,bwScale:1.45,desc:"Fast backbone with low latency."},
  overload:{label:"Overload",loss:0.08,latAdd:58,bwScale:0.28,desc:"Severe saturation and heavy drops."}
};

export const LAB_PRESETS = {
  voip:{label:"VoIP call",kind:"voip",proto:"UDP",rate:24,size:176,attack:false,desc:"RTP-like voice packets — low bitrate, latency-sensitive."},
  stream:{label:"Video stream",kind:"stream",proto:"UDP",rate:42,size:1180,attack:false,desc:"Continuous media stream — bandwidth-hungry and jitter-sensitive."},
  web:{label:"Web traffic",kind:"web",proto:"TCP",rate:8,size:900,attack:false,desc:"Normal web browsing burst and response pattern."},
  dos:{label:"DoS flood",kind:"dos",proto:"TCP",rate:120,size:72,attack:true,desc:"Single-source flood that overwhelms a target quickly."},
  ddos:{label:"DDoS flood",kind:"ddos",proto:"UDP",rate:220,size:1200,attack:true,desc:"Distributed flood from multiple sources to saturate links and services."},
  syn:{label:"SYN flood",kind:"syn-flood",proto:"TCP",rate:180,size:64,attack:true,desc:"Half-open TCP handshakes fill server queues and firewalls."},
  dnsamp:{label:"DNS amplification",kind:"dns-amplification",proto:"UDP",rate:150,size:128,attack:true,desc:"Small query, large response amplification pressure."}
};

export const LAB_STATE = {
  profile:"normal",
  flows:[],
  totalDrops:0,
  blocked:0,
  delivered:0,
  lastStatsAt:0,
  lastSummaryAt:0,
  lastLogAt:0,
  autoFirewall:true
};

export const SCENARIOS = {
  home:{name:"🏠 Home",desc:"ISP → Router NAT → AP → devices. DHCP, DNS, NAT basics.",nodes:[{id:"i",type:"cloud",x:410,y:50,label:"ISP / Internet",ip:"1.1.1.0/24"},{id:"r",type:"router",x:410,y:148,label:"Home Router",ip:"192.168.1.1"},{id:"a",type:"ap",x:410,y:255,label:"WiFi AP",ip:"192.168.1.2"},{id:"p1",type:"pc",x:195,y:370,label:"Desktop",ip:"192.168.1.10"},{id:"p2",type:"laptop",x:370,y:385,label:"Laptop",ip:"192.168.1.11"},{id:"p3",type:"pc",x:545,y:370,label:"Smart TV",ip:"192.168.1.12"},{id:"d",type:"dns",x:630,y:75,label:"DNS 8.8.8.8",ip:"8.8.8.8"}],edges:[{id:"e1",s:"i",t:"r",l:"WAN PPPoE"},{id:"e2",s:"i",t:"d",l:"DNS"},{id:"e3",s:"r",t:"a",l:"Eth GigE"},{id:"e4",s:"a",t:"p1",l:"2.4GHz"},{id:"e5",s:"a",t:"p2",l:"5GHz"},{id:"e6",s:"a",t:"p3",l:"2.4GHz"}]},
  enterprise:{name:"🏢 Enterprise",desc:"3-zone DMZ: Edge FW → DMZ (public servers) + Core LAN with VLANs.",nodes:[{id:"i",type:"cloud",x:410,y:38,label:"Internet",ip:"0.0.0.0/0"},{id:"fw",type:"ngfw",x:410,y:118,label:"Edge NGFW",ip:"203.0.113.1"},{id:"dr",type:"router",x:195,y:210,label:"DMZ Router",ip:"10.10.0.1"},{id:"cr",type:"l3sw",x:625,y:210,label:"Core L3 SW",ip:"172.16.0.1"},{id:"web",type:"web",x:90,y:320,label:"Web Server",ip:"10.10.0.10"},{id:"mail",type:"server",x:280,y:320,label:"Mail Server",ip:"10.10.0.11"},{id:"sw1",type:"switch",x:625,y:320,label:"Access SW1",ip:null},{id:"v10",type:"pc",x:480,y:430,label:"Finance VLAN10",ip:"172.16.10.5"},{id:"v20",type:"pc",x:630,y:430,label:"HR VLAN20",ip:"172.16.20.5"},{id:"v30",type:"server",x:780,y:430,label:"Files VLAN30",ip:"172.16.30.10"},{id:"dns",type:"dns",x:680,y:118,label:"Internal DNS",ip:"172.16.0.53"}],edges:[{id:"e1",s:"i",t:"fw",l:"WAN"},{id:"e2",s:"fw",t:"dr",l:"DMZ Zone"},{id:"e3",s:"fw",t:"cr",l:"LAN Zone"},{id:"e4",s:"fw",t:"dns",l:"Mgmt"},{id:"e5",s:"dr",t:"web",l:"GigE"},{id:"e6",s:"dr",t:"mail",l:"GigE"},{id:"e7",s:"cr",t:"sw1",l:"10G Trunk"},{id:"e8",s:"sw1",t:"v10",l:"VLAN10"},{id:"e9",s:"sw1",t:"v20",l:"VLAN20"},{id:"e10",s:"sw1",t:"v30",l:"VLAN30"}]},
  vpn:{name:"🔒 VPN",desc:"Site-to-site IPsec VPN. Encrypted tunnel over the public Internet.",nodes:[{id:"i",type:"cloud",x:410,y:52,label:"Internet",ip:"public"},{id:"hq",type:"router",x:185,y:162,label:"HQ Gateway",ip:"203.0.113.1"},{id:"br",type:"router",x:635,y:162,label:"Branch GW",ip:"198.51.100.1"},{id:"sw1",type:"switch",x:185,y:278,label:"HQ Switch",ip:null},{id:"sw2",type:"switch",x:635,y:278,label:"Branch Switch",ip:null},{id:"h1",type:"pc",x:80,y:390,label:"HQ PC 1",ip:"10.1.0.10"},{id:"h2",type:"pc",x:200,y:390,label:"HQ PC 2",ip:"10.1.0.11"},{id:"s1",type:"server",x:320,y:390,label:"HQ Server",ip:"10.1.0.5"},{id:"b1",type:"pc",x:510,y:390,label:"Branch PC1",ip:"10.2.0.10"},{id:"b2",type:"pc",x:635,y:390,label:"Branch PC2",ip:"10.2.0.11"},{id:"b3",type:"pc",x:760,y:390,label:"Branch PC3",ip:"10.2.0.12"}],edges:[{id:"e1",s:"hq",t:"i",l:"WAN"},{id:"e2",s:"br",t:"i",l:"WAN"},{id:"e3",s:"hq",t:"sw1",l:"LAN"},{id:"e4",s:"br",t:"sw2",l:"LAN"},{id:"e5",s:"sw1",t:"h1",l:"Eth"},{id:"e6",s:"sw1",t:"h2",l:"Eth"},{id:"e7",s:"sw1",t:"s1",l:"Eth"},{id:"e8",s:"sw2",t:"b1",l:"Eth"},{id:"e9",s:"sw2",t:"b2",l:"Eth"},{id:"e10",s:"sw2",t:"b3",l:"Eth"}],vpn:["hq","br"]},
  datacenter:{name:"🏗️ Datacenter",desc:"Spine-leaf fabric with load balancer, app tier, and DB cluster.",nodes:[{id:"i",type:"cloud",x:410,y:36,label:"Internet",ip:"0.0.0.0/0"},{id:"fw",type:"ngfw",x:410,y:108,label:"DC Firewall",ip:"10.0.0.1"},{id:"lb",type:"lb",x:410,y:190,label:"Load Balancer",ip:"10.0.1.1"},{id:"sp1",type:"l3sw",x:225,y:278,label:"Spine-1",ip:"10.0.10.1"},{id:"sp2",type:"l3sw",x:595,y:278,label:"Spine-2",ip:"10.0.10.2"},{id:"lf1",type:"switch",x:130,y:378,label:"Leaf-1",ip:null},{id:"lf2",type:"switch",x:320,y:378,label:"Leaf-2",ip:null},{id:"lf3",type:"switch",x:500,y:378,label:"Leaf-3",ip:null},{id:"lf4",type:"switch",x:690,y:378,label:"Leaf-4",ip:null},{id:"a1",type:"web",x:80,y:485,label:"App-1",ip:"10.0.2.11"},{id:"a2",type:"web",x:185,y:485,label:"App-2",ip:"10.0.2.12"},{id:"a3",type:"web",x:270,y:485,label:"App-3",ip:"10.0.2.13"},{id:"a4",type:"web",x:375,y:485,label:"App-4",ip:"10.0.2.14"},{id:"db1",type:"server",x:455,y:485,label:"DB Primary",ip:"10.0.3.11"},{id:"db2",type:"server",x:560,y:485,label:"DB Replica",ip:"10.0.3.12"},{id:"s3",type:"server",x:645,y:485,label:"Cache",ip:"10.0.4.11"},{id:"s4",type:"server",x:750,y:485,label:"Object Store",ip:"10.0.4.12"}],edges:[{id:"e0",s:"i",t:"fw",l:"WAN"},{id:"e1",s:"fw",t:"lb",l:"Filtered"},{id:"e2",s:"lb",t:"sp1",l:"10G"},{id:"e3",s:"lb",t:"sp2",l:"10G"},{id:"e4",s:"sp1",t:"lf1",l:"40G"},{id:"e5",s:"sp1",t:"lf2",l:"40G"},{id:"e6",s:"sp1",t:"lf3",l:"40G"},{id:"e7",s:"sp2",t:"lf2",l:"40G"},{id:"e8",s:"sp2",t:"lf3",l:"40G"},{id:"e9",s:"sp2",t:"lf4",l:"40G"},{id:"e10",s:"lf1",t:"a1",l:"1G"},{id:"e11",s:"lf1",t:"a2",l:"1G"},{id:"e12",s:"lf2",t:"a3",l:"1G"},{id:"e13",s:"lf2",t:"a4",l:"1G"},{id:"e14",s:"lf3",t:"db1",l:"25G"},{id:"e15",s:"lf3",t:"db2",l:"25G"},{id:"e16",s:"lf4",t:"s3",l:"10G"},{id:"e17",s:"lf4",t:"s4",l:"10G"}]},
  hybrid:{name:"☁️ Hybrid Cloud",desc:"On-prem datacenter connected to a cloud VPC with VPN/Direct Connect and a public load balancer.",nodes:[{id:"i",type:"cloud",x:410,y:36,label:"Public Cloud (VPC)",ip:"0.0.0.0/0"},{id:"dc-fw",type:"ngfw",x:300,y:120,label:"On-prem FW",ip:"198.51.100.1"},{id:"vpc-fw",type:"ngfw",x:520,y:120,label:"Cloud FW",ip:"203.0.113.1"},{id:"dc-lb",type:"lb",x:300,y:200,label:"On-prem LB",ip:"10.100.1.10"},{id:"vpc-lb",type:"lb",x:520,y:200,label:"Cloud LB",ip:"34.120.1.10"},{id:"dc-web",type:"web",x:220,y:300,label:"App (On-prem)",ip:"10.100.2.10"},{id:"dc-db",type:"server",x:380,y:300,label:"DB (On-prem)",ip:"10.100.3.11"},{id:"vpc-app1",type:"web",x:440,y:300,label:"Cloud App 1",ip:"10.200.2.11"},{id:"vpc-db",type:"server",x:600,y:300,label:"Cloud DB",ip:"10.200.3.11"}],edges:[{id:"e1",s:"dc-fw",t:"vpc-fw",l:"IPsec VPN / Direct"},{id:"e2",s:"dc-fw",t:"dc-lb",l:"Uplink"},{id:"e3",s:"vpc-fw",t:"vpc-lb",l:"Cloud Uplink"},{id:"e4",s:"dc-lb",t:"dc-web",l:"1G"},{id:"e5",s:"dc-lb",t:"dc-db",l:"1G"},{id:"e6",s:"vpc-lb",t:"vpc-app1",l:"10G"},{id:"e7",s:"vpc-lb",t:"vpc-db",l:"10G"}]},
  wan:{name:"🌐 WAN/BGP",desc:"3-site MPLS WAN with BGP routing between Autonomous Systems.",nodes:[{id:"mpls",type:"cloud",x:410,y:44,label:"MPLS Core",ip:"AS65000"},{id:"pe1",type:"router",x:165,y:152,label:"HQ PE (AS65001)",ip:"10.255.1.1"},{id:"pe2",type:"router",x:410,y:215,label:"Br1 PE (AS65002)",ip:"10.255.2.1"},{id:"pe3",type:"router",x:655,y:152,label:"Br2 PE (AS65003)",ip:"10.255.3.1"},{id:"fw1",type:"firewall",x:165,y:270,label:"HQ Firewall",ip:"10.1.0.1"},{id:"sw1",type:"l3sw",x:165,y:370,label:"HQ Core SW",ip:"10.1.0.2"},{id:"h1",type:"pc",x:62,y:462,label:"HQ PC1",ip:"10.1.0.10"},{id:"h2",type:"pc",x:175,y:462,label:"HQ PC2",ip:"10.1.0.11"},{id:"s1",type:"server",x:288,y:462,label:"HQ Server",ip:"10.1.0.5"},{id:"sw2",type:"switch",x:410,y:335,label:"Br1 Switch",ip:null},{id:"b1",type:"pc",x:318,y:445,label:"Br1 PC1",ip:"10.2.0.10"},{id:"b2",type:"pc",x:500,y:445,label:"Br1 PC2",ip:"10.2.0.11"},{id:"sw3",type:"switch",x:655,y:270,label:"Br2 Switch",ip:null},{id:"c1",type:"pc",x:568,y:378,label:"Br2 PC1",ip:"10.3.0.10"},{id:"c2",type:"pc",x:742,y:378,label:"Br2 PC2",ip:"10.3.0.11"}],edges:[{id:"e1",s:"mpls",t:"pe1",l:"MPLS P2P"},{id:"e2",s:"mpls",t:"pe2",l:"MPLS P2P"},{id:"e3",s:"mpls",t:"pe3",l:"MPLS P2P"},{id:"e4",s:"pe1",t:"fw1",l:"WAN GW"},{id:"e5",s:"fw1",t:"sw1",l:"Trunk"},{id:"e6",s:"sw1",t:"h1",l:"Eth"},{id:"e7",s:"sw1",t:"h2",l:"Eth"},{id:"e8",s:"sw1",t:"s1",l:"Eth"},{id:"e9",s:"pe2",t:"sw2",l:"GigE"},{id:"e10",s:"sw2",t:"b1",l:"Eth"},{id:"e11",s:"sw2",t:"b2",l:"Eth"},{id:"e12",s:"pe3",t:"sw3",l:"GigE"},{id:"e13",s:"sw3",t:"c1",l:"Eth"},{id:"e14",s:"sw3",t:"c2",l:"Eth"}]},
  ospf:{name:"📍 OSPF",desc:"OSPF multi-area: backbone Area 0 with Areas 1 and 2 attached via ABRs.",nodes:[{id:"bb1",type:"router",x:300,y:95,label:"Backbone R1",ip:"10.0.0.1"},{id:"bb2",type:"router",x:520,y:95,label:"Backbone R2",ip:"10.0.0.2"},{id:"abr1",type:"router",x:165,y:220,label:"ABR Area0/1",ip:"10.0.1.1"},{id:"abr2",type:"router",x:655,y:220,label:"ABR Area0/2",ip:"10.0.2.1"},{id:"r1a",type:"router",x:80,y:345,label:"Area1 R-A",ip:"10.1.0.1"},{id:"r1b",type:"router",x:250,y:345,label:"Area1 R-B",ip:"10.1.0.2"},{id:"r2a",type:"router",x:570,y:345,label:"Area2 R-A",ip:"10.2.0.1"},{id:"r2b",type:"router",x:740,y:345,label:"Area2 R-B",ip:"10.2.0.2"},{id:"n1",type:"pc",x:80,y:450,label:"Net 10.1.1.0",ip:"10.1.1.x"},{id:"n2",type:"pc",x:250,y:450,label:"Net 10.1.2.0",ip:"10.1.2.x"},{id:"n3",type:"pc",x:570,y:450,label:"Net 10.2.1.0",ip:"10.2.1.x"},{id:"n4",type:"pc",x:740,y:450,label:"Net 10.2.2.0",ip:"10.2.2.x"}],edges:[{id:"e1",s:"bb1",t:"bb2",l:"Area 0"},{id:"e2",s:"bb1",t:"abr1",l:"Area 0"},{id:"e3",s:"bb2",t:"abr2",l:"Area 0"},{id:"e4",s:"abr1",t:"r1a",l:"Area 1"},{id:"e5",s:"abr1",t:"r1b",l:"Area 1"},{id:"e6",s:"abr2",t:"r2a",l:"Area 2"},{id:"e7",s:"abr2",t:"r2b",l:"Area 2"},{id:"e8",s:"r1a",t:"n1",l:"LAN"},{id:"e9",s:"r1b",t:"n2",l:"LAN"},{id:"e10",s:"r2a",t:"n3",l:"LAN"},{id:"e11",s:"r2b",t:"n4",l:"LAN"}]},
  spanning:{name:"🔁 STP",desc:"Spanning Tree Protocol: redundant switch topology, root bridge election, blocked ports.",nodes:[{id:"r",type:"router",x:410,y:48,label:"Router",ip:"10.0.0.1"},{id:"root",type:"switch",x:410,y:142,label:"Root Bridge SW0",ip:"Priority 0"},{id:"sw1",type:"switch",x:205,y:258,label:"SW1 (Non-Root)",ip:"Prio 32768"},{id:"sw2",type:"switch",x:615,y:258,label:"SW2 (Non-Root)",ip:"Prio 32768"},{id:"sw3",type:"switch",x:105,y:375,label:"SW3",ip:"Prio 32768"},{id:"sw4",type:"switch",x:310,y:375,label:"SW4",ip:"Prio 32768"},{id:"sw5",type:"switch",x:510,y:375,label:"SW5",ip:"Prio 32768"},{id:"sw6",type:"switch",x:715,y:375,label:"SW6",ip:"Prio 32768"},{id:"h1",type:"pc",x:55,y:480,label:"PC1",ip:"10.0.1.10"},{id:"h2",type:"pc",x:160,y:480,label:"PC2",ip:"10.0.1.11"},{id:"h3",type:"pc",x:260,y:480,label:"PC3",ip:"10.0.2.10"},{id:"h4",type:"pc",x:365,y:480,label:"PC4",ip:"10.0.2.11"},{id:"h5",type:"pc",x:460,y:480,label:"PC5",ip:"10.0.3.10"},{id:"h6",type:"pc",x:565,y:480,label:"PC6",ip:"10.0.3.11"},{id:"h7",type:"pc",x:665,y:480,label:"PC7",ip:"10.0.4.10"},{id:"h8",type:"pc",x:770,y:480,label:"PC8",ip:"10.0.4.11"}],edges:[{id:"e0",s:"r",t:"root",l:"Uplink"},{id:"e1",s:"root",t:"sw1",l:"Designated"},{id:"e2",s:"root",t:"sw2",l:"Designated"},{id:"e3",s:"sw1",t:"sw2",l:"[BLK] STP Block"},{id:"e4",s:"sw1",t:"sw3",l:"Designated"},{id:"e5",s:"sw1",t:"sw4",l:"Designated"},{id:"e6",s:"sw2",t:"sw5",l:"Designated"},{id:"e7",s:"sw2",t:"sw6",l:"Designated"},{id:"e8",s:"sw3",t:"h1",l:"Access"},{id:"e9",s:"sw3",t:"h2",l:"Access"},{id:"e10",s:"sw4",t:"h3",l:"Access"},{id:"e11",s:"sw4",t:"h4",l:"Access"},{id:"e12",s:"sw5",t:"h5",l:"Access"},{id:"e13",s:"sw5",t:"h6",l:"Access"},{id:"e14",s:"sw6",t:"h7",l:"Access"},{id:"e15",s:"sw6",t:"h8",l:"Access"}]}
};

export const ROUTING_TABLES = {
  home:[["0.0.0.0/0","via WAN ISP","S*","1"],["192.168.1.0/24","Connected LAN","C","0"],["8.8.8.8/32","via WAN ISP","S","1"]],
  enterprise:[["0.0.0.0/0","via ISP","S*","1"],["10.10.0.0/24","via DMZ iface","C","0"],["172.16.0.0/16","via LAN iface","C","0"],["203.0.113.0/24","eBGP peer","B","20"]],
  vpn:[["10.1.0.0/24","Loopback","C","0"],["10.2.0.0/24","via IPsec tunnel","S","1"],["0.0.0.0/0","via ISP WAN","S*","1"]],
  wan:[["10.1.0.0/16","Connected","C","0"],["10.2.0.0/16","via MPLS","L","1"],["10.3.0.0/16","via MPLS","L","1"],["0.0.0.0/0","via Tier1 BGP","B","20"]]
};

export const VLANS = {
  enterprise:[{id:1,name:"Native/Mgmt",c:"#64748b",ports:"All uplinks"},{id:10,name:"Finance",c:"#3b82f6",ports:"SW1 Fa0/1-10"},{id:20,name:"HR",c:"#10b981",ports:"SW1 Fa0/11-20"},{id:30,name:"Servers",c:"#f59e0b",ports:"SW1 Fa0/21-24"},{id:99,name:"DMZ",c:"#ef4444",ports:"Uplink to FW"}],
  datacenter:[{id:10,name:"App Servers",c:"#06b6d4",ports:"Leaf1-2 all"},{id:20,name:"Database",c:"#8b5cf6",ports:"Leaf3 all"},{id:30,name:"Storage",c:"#f97316",ports:"Leaf4 all"},{id:100,name:"Management",c:"#64748b",ports:"All spines"}],
  default:[{id:1,name:"Default VLAN",c:"#64748b",ports:"All ports"},{id:10,name:"Users",c:"#3b82f6",ports:"Access ports"},{id:20,name:"Servers",c:"#10b981",ports:"Trunk ports"}]
};

export const TCP_STEPS = [
  {from:"→",flags:"SYN",desc:"Client sends synchronize. Sets SYN=1, random Seq=1000, ACK=0.",detail:"The client initiates by sending a TCP segment with the SYN flag set. It picks a random Initial Sequence Number (ISN) — e.g. 1000. The ACK flag is 0 because there's nothing to acknowledge yet. The server must be in LISTEN state on the destination port."},
  {from:"←",flags:"SYN-ACK",desc:"Server acknowledges and sends its own SYN. Seq=5000, ACK=1001.",detail:"The server responds with SYN=1 and ACK=1 (both set). It acknowledges the client's ISN by setting ACK number = client ISN + 1 = 1001. It also chooses its own random ISN (e.g. 5000). Server enters SYN-RECEIVED state."},
  {from:"→",flags:"ACK",desc:"Client acknowledges server's SYN. Connection ESTABLISHED on both sides.",detail:"Client sets ACK=1, SYN=0. ACK number = server ISN + 1 = 5001. Both sides are now in ESTABLISHED state. They have agreed on sequence numbers for reliable ordered delivery."},
  {from:"→",flags:"DATA",desc:"Client sends data (e.g. 'GET / HTTP/1.1'). Seq=1001.",detail:"Data is carried in the TCP payload. The sender increments its Seq number by the number of bytes sent. The receiver must ACK each byte. If ACK is not received within RTO, the segment is retransmitted. Window size controls bytes in-flight."},
  {from:"←",flags:"ACK+DATA",desc:"Server ACKs client data and sends HTTP 200 response.",detail:"The server ACKs the received data and may send its response in the same segment (piggybacking). HTTP/2 and QUIC multiplex many streams over one connection to avoid head-of-line blocking."},
  {from:"→",flags:"FIN",desc:"Client initiates graceful teardown. Sends FIN to close its half.",detail:"Active closer sends FIN. Passive closer sends ACK (half-close). Passive closer then sends its own FIN when done sending. Active closer ACKs. This is the 4-way teardown."},
  {from:"←",flags:"FIN-ACK",desc:"Server ACKs FIN and sends its own FIN. Connection fully closed.",detail:"Server sends FIN+ACK. Client ACKs the server's FIN. Both sides free connection state. TIME_WAIT state keeps the port busy for 2×MSL (~60-120s) to absorb stale packets."}
];
